web/movieLib/urls.py
from django.urls import path

from . import views

app_name = 'movieLib'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.MovieView.as_view(), name='movie'),
    path('actors/', views.ActorIndexView.as_view(), name='actorIndex'),
    path('actor/<int:pk>', views.ActorView.as_view(), name='actor'),
    path('search', views.searchRouter, name='search'),
    path('search/movie/<str:keyword>', views.SearchMovieView.as_view(), name='searchMovie'),
    path('search/actor/<str:keyword>', views.SearchActorView.as_view(), name='searchActor'),
    path('search/comment/<str:keyword>', views.SearchCommentView.as_view(), name='searchComment'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('movieLib:index', permanent=False)),
    path('movie/', include('movieLib.urls')),
    path('admin/', admin.site.urls),
]

web/movieLib/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.views import generic

class Actor(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10, null=True)
    constellation = models.CharField(max_length=50, null=True)
    birthday = models.CharField(max_length=50, null=True)
    birthplace = models.CharField(max_length=200, null=True)
    profession = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=10000, null=True)
    imagePath = models.CharField(max_length=200, default='/static/image/404/actor.jpg')

    def __str__(self):
        return self.name

class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=20000, null=True)
    rating = models.FloatField(default=0, null=True)
    actors = models.ManyToManyField(Actor)
    genre = models.CharField(max_length=1000, null=True)
    imagePath = models.CharField(max_length=200, default='/static/image/404/movie.jpg')

    def __str__(self):
        return self.name

class Comment(models.Model):
    content = models.CharField(max_length=200)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

web/movieLib/views.py
import logging
import time

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse

from .models import Movie, Actor, Comment

logging.basicConfig(level=logging.DEBUG)

class IndexView(generic.ListView):
    model = Movie
    template_name = 'movieLib/index.html'
    paginate_by = 20
    ordering = ['-rating']

class ActorIndexView(generic.ListView):
    model = Actor
    template_name = 'movieLib/actorIndex.html'
    paginate_by = 20


class MovieView(generic.DetailView):
    model = Movie
    template_name = 'movieLib/movie.html'

class ActorView(generic.DetailView):
    model = Actor
    template_name = 'movieLib/actor.html'

    def getAdjacencyActors(self):
        bucket = dict()
        movies = Actor.objects.get(pk=self.kwargs.get('pk')).movie_set.all()
        for movie in movies:
            for actor in movie.actors.all() :
                if actor.id != self.kwargs.get('pk'):
                    if not actor.id in bucket:
                        bucket[actor.id] = 0
                    bucket[actor.id] += 1
        adjs = sorted(bucket.items(), key=lambda x: -x[1])[:10]
        for i, adj in enumerate(adjs):
            adjs[i] = (Actor.objects.get(pk=adj[0]), adj[1])
        return adjs

    def get_context_data(self, **kwargs):
        context = super(ActorView, self).get_context_data(**kwargs)
        context["adjacencyActors"] = self.getAdjacencyActors()
        return context

class SearchMovieView(generic.ListView):
    template_name = 'movieLib/search_movies_results.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(SearchMovieView, self).get_context_data(**kwargs)
        context['elapsed_time'] = self.elapsed_time
        context['res_size'] = self.res_size
        return context

    def get_queryset(self):
        time_st = time.time()
        keyword = self.kwargs.get('keyword')
        p1 = Movie.objects.filter(name__contains=keyword)
        p2 = Movie.objects.filter(actors__name__contains=keyword)
        res = (p1 | p2).distinct()
        time_ed = time.time()
        self.elapsed_time = time_ed - time_st
        self.res_size = len(res)
        return res

class SearchActorView(generic.ListView):
    template_name = 'movieLib/search_actors_results.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(SearchActorView, self).get_context_data(**kwargs)
        context['elapsed_time'] = self.elapsed_time
        context['res_size'] = self.res_size
        return context

    def get_queryset(self):
        time_st = time.time()
        keyword = self.kwargs.get('keyword')
        keyword = self.kwargs.get('keyword')
        p1 = Actor.objects.filter(name__contains=keyword)
        p2 = Actor.objects.filter(movie__name__contains=keyword)
        res = (p1 | p2).distinct()
        time_ed = time.time()
        self.elapsed_time = time_ed - time_st
        self.res_size = len(res)
        return res

class SearchCommentView(generic.ListView):
    template_name = 'movieLib/search_comments_results.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(SearchCommentView, self).get_context_data(**kwargs)
        context['elapsed_time'] = self.elapsed_time
        context['res_size'] = self.res_size
        return context

    def get_queryset(self):
        time_st = time.time()
        keyword = self.kwargs.get('keyword')
        queryset = Comment.objects.filter(content__contains=keyword)
        time_ed = time.time()
        self.elapsed_time = time_ed - time_st
        self.res_size = len(queryset)
        return queryset

def searchRouter(request):
    keyword = request.GET["search"]
    category = request.GET["category"]

    if category == "movie":
        return HttpResponseRedirect(reverse('movieLib:searchMovie', args=(keyword,)))

    if category == "actor":
        return HttpResponseRedirect(reverse('movieLib:searchActor', args=(keyword,)))

    if category == "comment":
        return HttpResponseRedirect(reverse('movieLib:searchComment', args=(keyword,)))

web/movieLib/templates/movieLib/actor.html
{% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'css/actor.css'%}">

<div id='navibar'>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:index' %}">Movies</a>
	</div>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:actorIndex' %}">Actors</a>
	</div>

	<div class = 'navitem search'>
		<form action = '{% url 'movieLib:search' %}' method = 'get'>
			{% csrf_token %}
			<input type = 'radio' name = 'category' id = 0 checked value = "movie">Movie
			<input type = 'radio' name = 'category' id = 1 value = "actor">Actor
			<input type = 'radio' name = 'category' id = 2 value = "comment">Comment
			<input type = "search" placeholder = "Search" required name = 'search'>
			<button type = "submit">Search</button>
		</form>
	</div>


</div>

<div class = 'area'>
	<div class = 'cover'>		
		<img src = "{{ actor.imagePath }}">
	</div>
	<div class = 'info'> 
		<ul>
			<li><b>姓名：</b>{{ actor.name }}</li>
			<li><b>性别：</b>{{ actor.gender }}</li>
			<li><b>生日：</b>{{ actor.birthday }}</li>
			<li><b>星座：</b>{{ actor.constellation }}</li>
			<li><b>出生地：</b>{{ actor.birthplace }}</li>
			<li><b>职业：</b>{{ actor.profession }}</li>
		</ul>
	</div>
</div>

<div class = 'area'>{{ actor.description | linebreaks }}</div>

<div class = 'area'>
	{% for movie in actor.movie_set.all %}
	<div class = 'movie'>
		<a href = "{% url 'movieLib:movie' movie.id %}">
			<figure>
				<img src = '{{movie.imagePath}}'>
				<figCaption>{{ movie.name }}</figCaption>
			</figure>
		</a>
	</div>
	{% endfor %}
</div>

<div class = 'area'>
	{% for actor, cnt in adjacencyActors %}
	<div class = 'actor'>
		<a href = "{% url 'movieLib:actor' actor.id %}">
			<figure>
				<img src = '{{ actor.imagePath }}'>
				<figCaption> {{ actor.name }} <br>合作作品数({{ cnt }}) </figCaption>
			</figure>
		</a>
	</div>
	{% endfor %}
</div>

web/movieLib/templates/movieLib/actorIndex.html
{% load static %}

<header>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/actorIndex.css' %}">
</header>

<div id='navibar'>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:index' %}">Movies</a>
	</div>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:actorIndex' %}">Actors</a>
	</div>

	<div class = 'navitem search'>
		<form action = '{% url 'movieLib:search' %}' method = 'get'>
			{% csrf_token %}
			<input type = 'radio' name = 'category' id = 0 checked value = "movie">Movie
			<input type = 'radio' name = 'category' id = 1 value = "actor">Actor
			<input type = 'radio' name = 'category' id = 2 value = "comment">Comment
			<input type = "search" placeholder = "Search" required name = 'search'>
			<button type = "submit">Search</button>
		</form>
	</div>


</div>

<div id='actor_container' class = 'effect'>
	{% for actor in page_obj %}
	<div class='actor_item'>
		<a href = "{% url 'movieLib:actor' actor.id %}">
			<figure>
				<img src = "{{ actor.imagePath }}">
				<figCaption>{{ actor.name }}</figCaption>
			</figure>
		</a>
	</div>
	{% endfor %}
</div>

<div class="pagination">
	<div class = 'page'><a href="?page=1">1</a></div>

	<div style = "display:flex; margin: auto">
		{% if page_obj.has_previous %}
		<div class = 'page'><a href="?page={{ page_obj.previous_page_number }}"> {{ page_obj.previous_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

		<div class = 'page'><a href="?page={{ page_obj.number }}"><b>{{ page_obj.number}}</b></a></div>

		{% if page_obj.has_next %}
		<div class = 'page'><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

	</div>

	<div class = 'page'><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>

	<div style = "diaplay:flex; width: 90px; margin-left: 40px;">
		<input type = 'text' id = 'pageText' name = 'page' style = "margin-top: 7px; margin-bottom: 7px; width: 30px; boxing-size: border-box; vertical-align: top;"> 
		<button onclick = "window.location.replace(`?page=${document.getElementById('pageText').value}`)" style = "width: 30px; height: 21px; margin-top: 7px; margin-bottom: 7px; font-size: 10; text-align: center">Go</button>
	</div>

</div>

web/movieLib/templates/movieLib/index.html
{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'css/index.css' %}">

<div id='navibar'>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:index' %}">Movies</a>
	</div>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:actorIndex' %}">Actors</a>
	</div>

	<div class = 'navitem search'>
		<form action = '{% url 'movieLib:search' %}' method = 'get'>
			{% csrf_token %}
			<input type = 'radio' name = 'category' id = 0 checked value = "movie">Movie
			<input type = 'radio' name = 'category' id = 1 value = "actor">Actor
			<input type = 'radio' name = 'category' id = 2 value = "comment">Comment
			<input type = "search" placeholder = "Search" required name = 'search'>
			<button type = "submit">Search</button>
		</form>
	</div>


</div>

<div id='movie_container' class = 'effect'>
	{% for movie in page_obj %}
	<div class='movie_item'>
		<a href = "{% url 'movieLib:movie' movie.id %}">
			<figure>
				<img src = "{{ movie.imagePath }}">
				<figCaption>{{ movie.name }}</figCaption>
			</figure>
		</a>
	</div>
	{% endfor %}
</div>

<div class="pagination">
	<div class = 'page'><a href="?page=1">1</a></div>

	<div style = "display:flex; margin: auto">
		{% if page_obj.has_previous %}
		<div class = 'page'><a href="?page={{ page_obj.previous_page_number }}"> {{ page_obj.previous_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

		<div class = 'page'><a href="?page={{ page_obj.number }}"><b>{{ page_obj.number}}</b></a></div>

		{% if page_obj.has_next %}
		<div class = 'page'><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

	</div>

	<div class = 'page'><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>

	<div style = "diaplay:flex; width: 90px; margin-left: 40px;">
		<input type = 'text' id = 'pageText' name = 'page' style = "margin-top: 7px; margin-bottom: 7px; width: 30px; boxing-size: border-box; vertical-align: top;"> 
		<button onclick = "window.location.replace(`?page=${document.getElementById('pageText').value}`)" style = "width: 30px; height: 21px; margin-top: 7px; margin-bottom: 7px; font-size: 10; text-align: center">Go</button>
	</div>

</div>

web/movieLib/templates/movieLib/movie.html
{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'css/movie.css'%}">

<div class = 'background' style = "background-image: url({{ movie.imagePath }})">
	<div class = 'blur'>

		<div class = 'movie_cover'>
			<img src = "{{ movie.imagePath }}" class = "effect">
		</div>

		<div class = 'movie_info'>
			<h1>{{ movie.name }}</h1>

			<div class = "description">   {{movie.description}}</div>
		</div>

		<div class = 'actors_and_rating'>

			<div class = 'rating' style = "background-image: url(/static/image/resource/leaves.png)">
				<div class = 'rating_text'>{{ movie.rating }}</div>
				<div class = 'genre_text'>{{ movie.genre }}</div>
			</div>

			<div class = 'actors'>
				{% for actor in movie.actors.all %}
				<div class = 'actor'>
					<a href = "{% url 'movieLib:actor' actor.id %}">
						<figure>
							<img src = '{{ actor.imagePath }}'>
						</figure>
					</a>
				</div>	
				{% endfor %}
			</div>

		</div>

	</div>
</div>

<div id='navibar'>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:index' %}">Movies</a>
	</div>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:actorIndex' %}">Actors</a>
	</div>

	<div class = 'navitem search'>
		<form action = '{% url 'movieLib:search' %}' method = 'get'>
			{% csrf_token %}
			<input type = 'radio' name = 'category' id = 0 checked value = "movie">Movie
			<input type = 'radio' name = 'category' id = 1 value = "actor">Actor
			<input type = 'radio' name = 'category' id = 2 value = "comment">Comment
			<input type = "search" placeholder = "Search" required name = 'search'>
			<button type = "submit">Search</button>
		</form>
	</div>


</div>


<div class = 'comments'>

	<p style="background-image: url('{{ movie.imagePath }}')">短评<p>
	{% for comment in movie.comment_set.all %}
	<hr class = 'myStyle'>
	<div class = 'comment'>{{ comment.content }}</div>
	{% endfor %}
	<hr class = 'myStyle'>

</div>

web/movieLib/templates/movieLib/search.html
{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'css/search.css'%}">

web/movieLib/templates/movieLib/search_actors_results.html
{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'css/search_actors_results.css'%}">

<div id='navibar'>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:index' %}">Movies</a>
	</div>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:actorIndex' %}">Actors</a>
	</div>

	<div class = 'navitem search'>
		<form action = '{% url 'movieLib:search' %}' method = 'get'>
			{% csrf_token %}
			<input type = 'radio' name = 'category' id = 0 checked value = "movie">Movie
			<input type = 'radio' name = 'category' id = 1 value = "actor">Actor
			<input type = 'radio' name = 'category' id = 2 value = "comment">Comment
			<input type = "search" placeholder = "Search" required name = 'search'>
			<button type = "submit">Search</button>
		</form>
	</div>

</div>

<div class = 'container'>

	<div class = 'search_info effect'> About {{ res_size }} results ({{ elapsed_time }} second) </div>

	{% for actor in page_obj %}
	<div class = 'area'>
		<div class = 'cover'>		
			<img src = "{{ actor.imagePath }}">
		</div>
		<div class = 'info'> 
			<ul>
				<li><b>姓名：</b><a href = "{% url 'movieLib:actor' actor.id %}">{{ actor.name }}</a></li>
				<li><b>性别：</b>{{ actor.gender }}</li>
				<li><b>生日：</b>{{ actor.birthday }}</li>
				<li><b>星座：</b>{{ actor.constellation }}</li>
				<li><b>出生地：</b>{{ actor.birthplace }}</li>
				<li><b>职业：</b>{{ actor.profession }}</li>
			</ul>
		</div>
	</div>
	{% endfor %}
</div>

<div class="pagination">
	<div class = 'page'><a href="?page=1">1</a></div>

	<div style = "display:flex; margin: auto">
		{% if page_obj.has_previous %}
		<div class = 'page'><a href="?page={{ page_obj.previous_page_number }}"> {{ page_obj.previous_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

		<div class = 'page'><a href="?page={{ page_obj.number }}"><b>{{ page_obj.number}}</b></a></div>

		{% if page_obj.has_next %}
		<div class = 'page'><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

	</div>

	<div class = 'page'><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>

	<div style = "diaplay:flex; width: 90px; margin-left: 40px;">
		<input type = 'text' id = 'pageText' name = 'page' style = "margin-top: 7px; margin-bottom: 7px; width: 30px; boxing-size: border-box; vertical-align: top;"> 
		<button onclick = "window.location.replace(`?page=${document.getElementById('pageText').value}`)" style = "width: 30px; height: 21px; margin-top: 7px; margin-bottom: 7px; font-size: 10; text-align: center">Go</button>
	</div>

</div>

web/movieLib/templates/movieLib/search_comments_results.html
{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'css/search_movies_results.css'%}">

<div id='navibar'>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:index' %}">Movies</a>
	</div>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:actorIndex' %}">Actors</a>
	</div>

	<div class = 'navitem search'>
		<form action = '{% url 'movieLib:search' %}' method = 'get'>
			{% csrf_token %}
			<input type = 'radio' name = 'category' id = 0 checked value = "movie">Movie
			<input type = 'radio' name = 'category' id = 1 value = "actor">Actor
			<input type = 'radio' name = 'category' id = 2 value = "comment">Comment
			<input type = "search" placeholder = "Search" required name = 'search'>
			<button type = "submit">Search</button>
		</form>
	</div>

</div>

<div class = 'container'>

	<div class = 'search_info effect'> About {{ res_size }} results ({{ elapsed_time }} second) </div>

	{% for comment in page_obj %}

	<div class = 'area'>
		<div class = 'cover'>		
			<img src = "{{ comment.movie.imagePath }}">
		</div>
		<div class = 'info'> 
			<ul>
				<li><b>名称：</b><a href = "{% url 'movieLib:movie' comment.movie.id %}">{{ comment.movie.name }}</a></li>
				<li><b>类型：</b>{{ comment.movie.genre }}</li>
				<li><b>评分：</b>{{ comment.movie.rating }}</li>
				<li><b>短评：</b><p>{{ comment.content }}</p></li>
			</ul>
		</div>
	</div>

	{% endfor %}
</div>

<div class="pagination">
	<div class = 'page'><a href="?page=1">1</a></div>

	<div style = "display:flex; margin: auto">
		{% if page_obj.has_previous %}
		<div class = 'page'><a href="?page={{ page_obj.previous_page_number }}"> {{ page_obj.previous_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

		<div class = 'page'><a href="?page={{ page_obj.number }}"><b>{{ page_obj.number}}</b></a></div>

		{% if page_obj.has_next %}
		<div class = 'page'><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

	</div>

	<div class = 'page'><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>

	<div style = "diaplay:flex; width: 90px; margin-left: 40px;">
		<input type = 'text' id = 'pageText' name = 'page' style = "margin-top: 7px; margin-bottom: 7px; width: 30px; boxing-size: border-box; vertical-align: top;"> 
		<button onclick = "window.location.replace(`?page=${document.getElementById('pageText').value}`)" style = "width: 30px; height: 21px; margin-top: 7px; margin-bottom: 7px; font-size: 10; text-align: center">Go</button>
	</div>

</div>

web/movieLib/templates/movieLib/search_movies_results.html
{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'css/search_movies_results.css'%}">

<div id='navibar'>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:index' %}">Movies</a>
	</div>

	<div class = 'navitem'>
		<a href = "{% url 'movieLib:actorIndex' %}">Actors</a>
	</div>

	<div class = 'navitem search'>
		<form action = '{% url 'movieLib:search' %}' method = 'get'>
			{% csrf_token %}
			<input type = 'radio' name = 'category' id = 0 checked value = "movie">Movie
			<input type = 'radio' name = 'category' id = 1 value = "actor">Actor
			<input type = 'radio' name = 'category' id = 2 value = "comment">Comment
			<input type = "search" placeholder = "Search" required name = 'search'>
			<button type = "submit">Search</button>
		</form>
	</div>

</div>

<div class = 'container'>

	<div class = 'search_info effect'> About {{ res_size }} results ({{ elapsed_time }} second) </div>

	{% for movie in page_obj %}

	<div class = 'area'>
		<div class = 'cover'>		
			<img src = "{{ movie.imagePath }}">
		</div>
		<div class = 'info'> 
			<ul>
				<li><b>名称：</b><a href = "{% url 'movieLib:movie' movie.id %}">{{ movie.name }}</a></li>
				<li><b>类型：</b>{{ movie.genre }}</li>
				<li><b>评分：</b>{{ movie.rating }}</li>
				<li><b>演员：</b>
					{% for actor in movie.actors.all %}
					{% ifnotequal forloop.counter 1 %}
					/
					{% endifnotequal %}
					<a href = "{% url 'movieLib:actor' actor.id %}">{{ actor.name }}</a>	
					{% endfor %}
				</li>
			</ul>
		</div>
	</div>

	{% endfor %}
</div>

<div class="pagination">
	<div class = 'page'><a href="?page=1">1</a></div>

	<div style = "display:flex; margin: auto">
		{% if page_obj.has_previous %}
		<div class = 'page'><a href="?page={{ page_obj.previous_page_number }}"> {{ page_obj.previous_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

		<div class = 'page'><a href="?page={{ page_obj.number }}"><b>{{ page_obj.number}}</b></a></div>

		{% if page_obj.has_next %}
		<div class = 'page'><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number}}</a></div>
		{% else %}
		<div class = 'page'></div>
		{% endif %}

	</div>

	<div class = 'page'><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>

	<div style = "diaplay:flex; width: 90px; margin-left: 40px;">
		<input type = 'text' id = 'pageText' name = 'page' style = "margin-top: 7px; margin-bottom: 7px; width: 30px; boxing-size: border-box; vertical-align: top;"> 
		<button onclick = "window.location.replace(`?page=${document.getElementById('pageText').value}`)" style = "width: 30px; height: 21px; margin-top: 7px; margin-bottom: 7px; font-size: 10; text-align: center">Go</button>
	</div>

</div>

web/movieLib/templates/movieLib/search_results.html
{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'css/search_results.css'%}">

{{ test }}